name: Feature request
description: Suggest an idea for this project
title: 'feat: '
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      Thanks for the suggestion! Please keep requests focused and include context.

- type: textarea
  id: problem
  attributes:
    label: Problem statement
    description: What problem are you trying to solve?
  validations:
    required: true

- type: textarea
  id: proposal
  attributes:
    label: Proposed solution
    description: What would you like to happen?
  validations:
    required: true

- type: textarea
  id: alternatives
  attributes:
    label: Alternatives considered
  validations:
    required: false

- type: textarea
  id: additional
  attributes:
    label: Additional context
  validations:
    required: false
